version: '3.6'
networks:
  kbase-dev:
    external: true
    name: kbase-dev
services:
  eapearsonwidgettest22:
    build:
      context: .
    container_name: eapearsonwidgettest22
    hostname: eapearsonwidgettest22
    dns: 8.8.8.8
    volumes:
      - .:/kb/module
    networks:
      - kbase-dev
    ports:
      - "${PORT:-5100}:5000"
    environment:
      - KBASE_ENDPOINT
